export const plantSelector = {
  id: true,
  name: true,
  description: true,
  imageUrl: true,
  category: true,
  dateAdded: true,
  updatedAt: true,
  humidityRating: true,
  lightingRating: true,
  petToxicityRating: true,
  wateringRating: true,
  health: true,
  wateringFrequencyDays: true,
  lastWateredAt: true,
  nextWateringAt: true,
  userId: true,
}
