import '@testing-library/jest-native/extend-expect'

// Note: @expo/vector-icons is mocked via __mocks__/@expo/vector-icons.js
// to avoid act() warnings from async font loading

// Mock safe area context
jest.mock('react-native-safe-area-context', () => {
  const insets = { top: 0, right: 0, bottom: 0, left: 0 }
  return {
    SafeAreaProvider: ({ children }: { children: React.ReactNode }) => children,
    SafeAreaView: ({ children }: { children: React.ReactNode }) => children,
    useSafeAreaInsets: () => insets,
    useSafeAreaFrame: () => ({ x: 0, y: 0, width: 375, height: 812 }),
  }
})

// Mock theme
jest.mock('src/theme', () => ({
  colors: {
    primary: '#80ac53',
    primaryDark: '#6a9145',
    primaryLight: '#9bc76d',
    primaryTint: '#dceccb',
    coral: '#E8997E',
    coralDark: '#D88A6F',
    background: '#F8FAF8',
    backgroundDark: '#1A1A1A',
    surface: '#FFFFFF',
    surfaceDark: '#252A1F',
    surfaceTinted: '#F0F5F0',
    inputBackground: '#E8F0E8',
    textPrimary: '#1A1A1A',
    textSecondary: '#4A5568',
    textMuted: '#9CA3AF',
    textInverse: '#FFFFFF',
    textMain: '#1A1A1A',
    success: '#80ac53',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    waterBlue: '#60A5FA',
    fertilizerOrange: '#F59E0B',
    pruneRed: '#F87171',
    mistTeal: '#5EEAD4',
    achievementGold: '#FCD34D',
    white: '#FFFFFF',
    black: '#000000',
    border: '#E5E7EB',
    borderDark: '#374151',
  },
  iconColors: {
    primary: '#80ac53',
    primaryDark: '#6a9145',
    muted: '#9CA3AF',
    white: '#FFFFFF',
    error: '#EF4444',
    warning: '#F59E0B',
    success: '#80ac53',
    waterBlue: '#60A5FA',
    slate400: '#94a3b8',
    slate500: '#64748b',
    slate900: '#0f172a',
    coral: '#E8997E',
    fertilizerOrange: '#F59E0B',
    mistTeal: '#5EEAD4',
    pruneRed: '#F87171',
    border: '#E5E7EB',
    textPrimary: '#1A1A1A',
    textMuted: '#9CA3AF',
    textSecondary: '#4A5568',
    achievementGold: '#FCD34D',
    surfaceTinted: '#F0F5F0',
    info: '#3B82F6',
    background: '#F8FAF8',
  },
  fonts: {
    regular: 'PlusJakartaSans_400Regular',
    medium: 'PlusJakartaSans_500Medium',
    semiBold: 'PlusJakartaSans_600SemiBold',
    bold: 'PlusJakartaSans_700Bold',
    extraBold: 'PlusJakartaSans_800ExtraBold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 40,
    '3xl': 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    display: { size: 32, weight: '700', lineHeight: 1.2 },
    h1: { size: 28, weight: '700', lineHeight: 1.3 },
    h2: { size: 24, weight: '600', lineHeight: 1.3 },
    h3: { size: 20, weight: '600', lineHeight: 1.4 },
    h4: { size: 18, weight: '600', lineHeight: 1.4 },
    bodyLarge: { size: 16, weight: '400', lineHeight: 1.5 },
    body: { size: 14, weight: '400', lineHeight: 1.5 },
    bodySmall: { size: 12, weight: '400', lineHeight: 1.4 },
    caption: { size: 11, weight: '500', lineHeight: 1.3 },
    button: { size: 16, weight: '600', lineHeight: 1 },
  },
}))
